### ISSUE TITLE
Have you ever met this Ninja error?

### ISSUE THREAD

**Issue by Research-Code-123** [qizekun/ReCon#19]
Dear Author:

        Have you ever met this issue?

/usr/include/c++/9/bits/stl_bvector.h:108:38: internal compiler error: Segmentation fault
  108 |     operator<(const _Bit_reference& __x) const
      |                                      ^~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-9/README.Bugs> for instructions.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/root/anaconda3/envs/recon/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/Documents/MAE/ReCon/extensions/chamfer_dist/setup.py", line 11, in <module>
    setup(name='chamfer',
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
    self.run_command(cmd)
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/dist.py", line 945, in run_command
    super().run_command(command)
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
    cmd_obj.run()
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/command/install.py", line 92, in run
    self.do_egg_install()
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/command/install.py", line 144, in do_egg_install
    self.run_command('bdist_egg')
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/dist.py", line 945, in run_command
    super().run_command(command)
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
    cmd_obj.run()
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=False)
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/dist.py", line 945, in run_command
    super().run_command(command)
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
    cmd_obj.run()
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/command/install_lib.py", line 13, in run
    self.build()
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/_distutils/command/install_lib.py", line 110, in build
    self.run_command('build_ext')
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/dist.py", line 945, in run_command
    super().run_command(command)
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
    cmd_obj.run()
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 93, in run
    _build_ext.run(self)
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
    build_ext.build_extensions(self)
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
    self._build_extensions_serial()
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
    self.build_extension(ext)
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 254, in build_extension
    _build_ext.build_extension(self, ext)
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
    objects = self.compiler.compile(
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/root/anaconda3/envs/recon/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

Thanks.

**Comment by dreamcubeblock** [comment]
something wrong with your ubuntu system version or g++ version, or maybe you not install ninja

**Comment by Research-Code-123** [comment]
> something wrong with your ubuntu system version or g++ version, or maybe you not install ninja

Solved! Thanks!
